INSERT INTO film (launch_date, director, genre, title) VALUES
-- Peliculas
('1997-12-19', 'James Cameron', 'Drama romántico', 'Titanic'),
('1972-03-15', 'Francis Ford Coppola', 'Crimen, Drama', 'El Padrino'),
('1994-07-06', 'Robert Zemeckis', 'Comedia dramática', 'Forrest Gump'),
('2009-12-18', 'James Cameron', 'Ciencia ficción', 'Avatar'),
('2019-10-04', 'Todd Phillips', 'Thriller psicológico', 'Joker'),
('2003-12-17', 'Peter Jackson', 'Fantasía épica', 'El Señor de los Anillos: El retorno del Rey'),
('1994-10-14', 'Quentin Tarantino', 'Crimen, Drama', 'Pulp Fiction'),
('1994-11-30', 'Steven Spielberg', 'Drama histórico', 'La lista de Schindler'),
('1999-03-31', 'The Wachowskis', 'Ciencia ficción, Acción', 'Matrix'),
('1994-06-15', 'Roger Allers, Rob Minkoff', 'Animación, Drama', 'El Rey León'),
('1999-10-15', 'David Fincher', 'Drama psicológico', 'El club de la lucha'),
('2014-11-07', 'Christopher Nolan', 'Ciencia ficción, Drama', 'Interestelar'),
('1977-05-25', 'George Lucas', 'Ciencia ficción, Fantasía', 'La guerra de las galaxias'),
('1991-02-14', 'Jonathan Demme', 'Thriller psicológico', 'El silencio de los corderos'),
('2002-02-05', 'Fernando Meirelles, Kátia Lund', 'Drama criminal', 'Ciudad de Dios'),
('1985-07-03', 'Robert Zemeckis', 'Ciencia ficción, Comedia', 'Volver al futuro'),
('2016-12-09', 'Damien Chazelle', 'Musical, Romance', 'La La Land'),
('1980-06-13', 'Stanley Kubrick', 'Terror psicológico', 'El resplandor'),
('2004-11-05', 'Brad Bird', 'Animación, Acción', 'Los increíbles'),
('1971-12-19', 'Stanley Kubrick', 'Ciencia ficción, Drama', 'La naranja mecánica');

INSERT INTO review (film_id, rating, review_date, tv_series_id, dtype, comment, username) VALUES
-- Revies para peliculas
(1, 9, '2024-05-11', NULL, 'FilmReview', 'Una película emocionante con una gran historia y actuaciones increíbles.', 'emma'),
(2, 10, '2024-05-11', NULL, 'FilmReview', 'Una obra maestra del cine, impecablemente dirigida y actuada.', 'robert'),
(3, 8, '2024-05-11', NULL, 'FilmReview', 'Una película conmovedora y entretenida que deja una impresión duradera.', 'angelina'),
(4, 9, '2024-05-11', NULL, 'FilmReview', 'Visualmente impresionante y emocionalmente cautivadora.', 'leo'),
(5, 9, '2024-05-11', NULL, 'FilmReview', 'Una interpretación magistral del icónico personaje, una película que te deja pensando.', 'emma'),
(6, 10, '2024-05-11', NULL, 'FilmReview', 'Una conclusión épica a una trilogía inolvidable.', 'robert'),
(7, 9, '2024-05-11', NULL, 'FilmReview', 'Un clásico moderno que sigue siendo tan impactante como el primer día.', 'angelina'),
(8, 10, '2024-05-11', NULL, 'FilmReview', 'Una poderosa historia de redención que nunca pierde su relevancia.', 'leo'),
(9, 9, '2024-05-11', NULL, 'FilmReview', 'Una experiencia cinemática revolucionaria que redefine el género.', 'emma'),
(10, 9, '2024-05-11', NULL, 'FilmReview', 'Una joya animada que cautiva a espectadores de todas las edades.', 'robert'),
(11, 10, '2024-05-11', NULL, 'FilmReview', 'Una película que te hace cuestionar la realidad y la identidad.', 'angelina'),
(12, 9, '2024-05-11', NULL, 'FilmReview', 'Una odisea emocional y visualmente impresionante.', 'leo'),
(13, 10, '2024-05-11', NULL, 'FilmReview', 'Una galáctica aventura que cambió para siempre el cine.', 'emma'),
(14, 9, '2024-05-11', NULL, 'FilmReview', 'Un thriller psicológico que te mantendrá al borde de tu asiento.', 'robert'),
(15, 8, '2024-05-11', NULL, 'FilmReview', 'Una mirada cruda y realista a la vida en las favelas de Río de Janeiro.', 'angelina'),
(16, 10, '2024-05-11', NULL, 'FilmReview', 'Un viaje emocionante y lleno de diversión a través del tiempo.', 'leo'),
(17, 9, '2024-05-11', NULL, 'FilmReview', 'Un homenaje encantador al Hollywood clásico con una moderna sensibilidad.', 'emma'),
(18, 10, '2024-05-11', NULL, 'FilmReview', 'Una obra maestra del terror que te dejará sin aliento.', 'robert'),
(19, 9, '2024-05-11', NULL, 'FilmReview', 'Una familia de superhéroes como ninguna otra, llena de acción y diversión.', 'angelina'),
(20, 10, '2024-05-11', NULL, 'FilmReview', 'Un impactante y provocativo comentario social sobre la violencia y la libre voluntad.', 'leo'),
(1, 8, '2024-05-10', NULL, 'FilmReview', 'Una película emocionante con una gran historia, aunque algunas escenas son predecibles.', 'emma'),
(2, 9, '2024-05-10', NULL, 'FilmReview', 'Una de las mejores películas de todos los tiempos, con actuaciones excepcionales.', 'robert'),
(3, 7, '2024-05-10', NULL, 'FilmReview', 'Una película entretenida, pero con algunos momentos aburridos.', 'angelina'),
(4, 8, '2024-05-10', NULL, 'FilmReview', 'Visualmente impresionante, aunque la trama podría haber sido más original.', 'leo'),
(5, 9, '2024-05-10', NULL, 'FilmReview', 'Joaquin Phoenix ofrece una actuación inolvidable en esta película impactante.', 'emma'),
(6, 9, '2024-05-10', NULL, 'FilmReview', 'Un final satisfactorio para una trilogía que ha dejado huella en la historia del cine.', 'robert'),
(7, 8, '2024-05-10', NULL, 'FilmReview', 'Aunque algo larga, esta película sigue siendo relevante y emocionante.', 'angelina'),
(8, 9, '2024-05-10', NULL, 'FilmReview', 'Una historia poderosa que te hace reflexionar sobre la humanidad.', 'leo'),
(9, 8, '2024-05-10', NULL, 'FilmReview', 'Una experiencia cinematográfica innovadora que vale la pena ver.', 'emma'),
(10, 9, '2024-05-10', NULL, 'FilmReview', 'Una película animada que trasciende las edades y los géneros.', 'robert'),
(11, 8, '2024-05-10', NULL, 'FilmReview', 'Un thriller psicológico que te mantendrá intrigado hasta el final.', 'angelina'),
(12, 9, '2024-05-10', NULL, 'FilmReview', 'Una película visualmente impresionante con una historia emocionalmente profunda.', 'leo'),
(13, 9, '2024-05-10', NULL, 'FilmReview', 'Una aventura épica que ha inspirado a generaciones de cinéfilos.', 'emma'),
(14, 8, '2024-05-10', NULL, 'FilmReview', 'Un clásico del género del suspense que te mantendrá en vilo.', 'robert'),
(15, 7, '2024-05-10', NULL, 'FilmReview', 'Una mirada impactante a la realidad de las calles de Río.', 'angelina'),
(16, 9, '2024-05-10', NULL, 'FilmReview', 'Una aventura divertida y emocionante que nunca pasa de moda.', 'leo'),
(17, 8, '2024-05-10', NULL, 'FilmReview', 'Un tributo encantador al glamour y la nostalgia de Hollywood.', 'emma'),
(18, 9, '2024-05-10', NULL, 'FilmReview', 'Una película aterradora que te dejará sin aliento hasta el final.', 'robert'),
(19, 8, '2024-05-10', NULL, 'FilmReview', 'Una historia emocionante con personajes entrañables y acción impresionante.', 'angelina'),
(20, 9, '2024-05-10', NULL, 'FilmReview', 'Un comentario provocador sobre la sociedad que te hará reflexionar.', 'leo');

INSERT INTO tv_series (finish_date, launch_date, number_episodes, number_seasons, dtype, animation_studio, genre, title) VALUES
-- Series de TV regulares
(NULL, '2005-03-27', 327, 15, 'TvSeries', NULL, 'Ciencia ficción, Drama', 'Doctor Who'),
(NULL, '2016-07-15', 46, 4, 'TvSeries', NULL, 'Ciencia ficción, Drama', 'Stranger Things'),
(NULL, '2013-01-20', 62, 5, 'TvSeries', NULL, 'Drama, Crimen', 'Breaking Bad'),
(NULL, '2008-09-22', 279, 12, 'TvSeries', NULL, 'Comedia, Romance', 'The Big Bang Theory'),
('2019-12-20', '2011-09-25', 84, 5, 'TvSeries', NULL, 'Drama, Crimen', 'Person of Interest'),
('2018-05-13', '2011-09-23', 171, 8, 'TvSeries', NULL, 'Drama, Misterio', 'Once Upon a Time'),
('2017-04-30', '2011-04-03', 152, 7, 'TvSeries', NULL, 'Drama, Fantasía', 'The Vampire Diaries'),
('2019-05-19', '2014-10-12', 100, 6, 'TvSeries', NULL, 'Drama, Crimen', 'The Affair'),
('2019-04-14', '2010-04-11', 118, 7, 'TvSeries', NULL, 'Drama, Acción', 'The Walking Dead'),
('2021-05-25', '2011-04-17', 236, 10, 'TvSeries', NULL, 'Drama, Fantasía', 'Game of Thrones'),

-- Animes
('2020-09-30', '2013-04-07', 366, 1, 'Anime', 'Studio Pierrot', 'Acción, Aventura', 'Naruto'),
('2017-03-18', '2009-04-05', 366, 1, 'Anime', 'Toei Animation', 'Acción, Aventura', 'One Piece'),
(NULL, '2012-10-05', 131, 1, 'Anime', 'A-1 Pictures', 'Acción, Fantasía', 'Sword Art Online'),
(NULL, '2003-10-04', 64, 1, 'Anime', 'Madhouse', 'Thriller, Psicológico', 'Death Note'),
(NULL, '2016-04-06', 12, 1, 'Anime', 'Wit Studio', 'Acción, Drama', 'Attack on Titan'),

-- Miniseries
('2019-11-10', '2019-10-20', 9, 1, 'MiniSerie', NULL, 'Drama, Historia', 'Chernobyl'),
('2020-05-31', '2020-05-31', 10, 1, 'MiniSerie', NULL, 'Drama, Crimen', 'The Undoing'),
('2015-04-30', '2015-04-30', 8, 1, 'MiniSerie', NULL, 'Drama, Misterio', 'The Night Manager'),
('2019-05-05', '2019-05-05', 7, 1, 'MiniSerie', NULL, 'Drama, Ciencia ficción', 'Chernobyl'),
('2017-02-19', '2017-02-19', 6, 1, 'MiniSerie', NULL, 'Drama, Crimen', 'Big Little Lies');

INSERT INTO review (film_id, rating, review_date, tv_series_id, dtype, comment, username) VALUES
-- Reviews para series de TV regulares
(NULL, 9, '2024-05-12', 1, 'TvSeriesReview', 'Una serie increíblemente emocionante con giros inesperados y personajes memorables.', 'emma'),
(NULL, 8, '2024-05-12', 1, 'TvSeriesReview', 'Aunque el final fue polémico, en general fue una serie épica que nunca olvidaré.', 'robert'),
(NULL, 7, '2024-05-12', 2, 'TvSeriesReview', 'Una serie clásica con un montón de aventuras y un protagonista carismático.', 'angelina'),
(NULL, 9, '2024-05-12', 2, 'TvSeriesReview', 'Me encanta la variedad de mundos y enemigos en esta serie, nunca me aburro.', 'leo'),
(NULL, 8, '2024-05-12', 3, 'TvSeriesReview', 'Stranger Things me transporta a los años 80 con su atmósfera nostálgica y su misterio intrigante.', 'emma'),
(NULL, 9, '2024-05-12', 3, 'TvSeriesReview', 'Una serie adictiva con un elenco talentoso y una trama emocionante.', 'robert'),
(NULL, 10, '2024-05-12', 4, 'TvSeriesReview', 'Una obra maestra del drama criminal, con una actuación inolvidable de Bryan Cranston.', 'angelina'),
(NULL, 9, '2024-05-12', 4, 'TvSeriesReview', 'Breaking Bad es una montaña rusa emocional que te mantendrá enganchado desde el primer episodio.', 'leo'),
(NULL, 7, '2024-05-12', 5, 'TvSeriesReview', 'Una serie divertida con personajes entrañables, aunque algunas temporadas son mejores que otras.', 'emma'),
(NULL, 8, '2024-05-12', 5, 'TvSeriesReview', 'The Big Bang Theory siempre me hace reír, pero a veces se vuelve repetitiva.', 'robert'),
(NULL, 9, '2024-05-12', 6, 'TvSeriesReview', 'Person of Interest es una serie de espionaje emocionante y bien escrita que nunca decepciona.', 'angelina'),
(NULL, 8, '2024-05-12', 6, 'TvSeriesReview', 'Aunque el final fue apresurado, la serie en su conjunto es emocionante y llena de acción.', 'leo'),
(NULL, 9, '2024-05-12', 7, 'TvSeriesReview', 'Once Upon a Time es un cuento de hadas moderno con personajes entrañables y una trama envolvente.', 'emma'),
(NULL, 8, '2024-05-12', 7, 'TvSeriesReview', 'Me encanta la forma en que esta serie combina la fantasía con el misterio y el drama.', 'robert'),
(NULL, 8, '2024-05-12', 8, 'TvSeriesReview', 'The Vampire Diaries es una serie adictiva con romance, drama y mucha acción sobrenatural.', 'angelina'),
(NULL, 7, '2024-05-12', 8, 'TvSeriesReview', 'Aunque algunas temporadas son más flojas que otras, en general es una serie emocionante y entretenida.', 'leo'),
(NULL, 9, '2024-05-12', 9, 'TvSeriesReview', 'The Affair es una exploración fascinante de las relaciones humanas y sus complejidades.', 'emma'),
(NULL, 8, '2024-05-12', 9, 'TvSeriesReview', 'Una serie intensa y emotiva que te atrapa desde el primer episodio hasta el último.', 'robert'),
(NULL, 8, '2024-05-12', 10, 'TvSeriesReview', 'The Walking Dead es una serie emocionante con momentos de gran suspense y acción.', 'angelina'),
(NULL, 7, '2024-05-12', 10, 'TvSeriesReview', 'Aunque algunos arcos argumentales se alargan demasiado, en general es una serie emocionante y adictiva.', 'leo'),

-- Reviews para animes
(NULL, 9, '2024-05-12', 11, 'TvSeriesReview', 'Naruto es una serie de anime épica llena de acción y emoción.', 'emma'),
(NULL, 8, '2024-05-12', 11, 'TvSeriesReview', 'Una serie con un gran desarrollo de personajes y batallas emocionantes.', 'robert'),
(NULL, 9, '2024-05-12', 12, 'TvSeriesReview', 'One Piece es una aventura increíble con una historia rica y diversa.', 'angelina'),
(NULL, 8, '2024-05-12', 12, 'TvSeriesReview', 'Una serie con un mundo vasto y personajes carismáticos.', 'leo'),
(NULL, 8, '2024-05-12', 13, 'TvSeriesReview', 'Sword Art Online es un emocionante viaje a un mundo de realidad virtual.', 'emma'),
(NULL, 7, '2024-05-12', 13, 'TvSeriesReview', 'Aunque algunas partes son predecibles, en general es una serie emocionante y entretenida.', 'robert'),
(NULL, 9, '2024-05-12', 14, 'TvSeriesReview', 'Death Note es un thriller psicológico fascinante con una trama intrigante.', 'angelina'),
(NULL, 8, '2024-05-12', 14, 'TvSeriesReview', 'Una serie que te mantiene en vilo hasta el último episodio.', 'leo'),
(NULL, 8, '2024-05-12', 15, 'TvSeriesReview', 'Attack on Titan es una serie de anime llena de acción y suspenso.', 'emma'),
(NULL, 7, '2024-05-12', 15, 'TvSeriesReview', 'Aunque algunas temporadas son más lentas, en general es una serie emocionante y épica.', 'robert'),

-- Reviews para miniseries
(NULL, 9, '2024-05-12', 16, 'TvSeriesReview', 'Chernobyl es una miniserie desgarradora y poderosa que todos deberían ver.', 'angelina'),
(NULL, 8, '2024-05-12', 16, 'TvSeriesReview', 'Una serie que te deja sin aliento con su representación de los eventos históricos.', 'leo'),
(NULL, 8, '2024-05-12', 17, 'TvSeriesReview', 'The Undoing es una miniserie emocionante con giros sorprendentes y actuaciones convincentes.', 'emma'),
(NULL, 7, '2024-05-12', 17, 'TvSeriesReview', 'Aunque el final fue un poco decepcionante, en general es una serie intrigante y bien hecha.', 'robert'),
(NULL, 9, '2024-05-12', 18, 'TvSeriesReview', 'The Night Manager es una miniserie elegante y emocionante con un gran elenco.', 'angelina'),
(NULL, 8, '2024-05-12', 18, 'TvSeriesReview', 'Una serie que te mantiene en vilo hasta el final.', 'leo'),
(NULL, 9, '2024-05-12', 19, 'TvSeriesReview', 'Chernobyl es una miniserie impactante y emocionante que te hará reflexionar.', 'emma'),
(NULL, 8, '2024-05-12', 19, 'TvSeriesReview', 'Una serie que te sumerge por completo en los eventos que llevaron al desastre.', 'robert'),
(NULL, 8, '2024-05-12', 20, 'TvSeriesReview', 'Big Little Lies es una miniserie intrigante y emotiva con actuaciones sobresalientes.', 'angelina'),
(NULL, 7, '2024-05-12', 20, 'TvSeriesReview', 'Aunque algunas partes son lentas, en general es una serie que vale la pena ver.', 'leo');
